import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";
import Link from "next/link";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};



export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {


    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
            >
                <Header headerHeight={64}>
                    <Link href="/" className="text-lg font-bold">DGLiP</Link>
                </Header>

                <div style={{ height: "64px" }} />
                {/* spacer to avoid content jump under fixed header */}

                <div className="main-page-padding root" >
                    {children}
                </div>


                {/* footer stuck at bottom if not enough content */}
                <div className="flex-grow" />

                <footer className="mt-16 h-24 text-center text-sm text-gray-500 bg-red-600 main-page-padding">
                    &copy; {new Date().getFullYear()} DGLIP
                </footer>
            </body>
        </html>
    );
}
