import type {Metadata} from "next";
import "./globals.css";
import Header from "@/app/components/Header";
import React from "react";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <html lang="en">
            <body
                className={`antialiased min-h-screen flex flex-col`}
            >
                <Header/>

                {/* spacer to avoid content jump under fixed header */}

                {children}

                {/* footer stuck at bottom if not enough content */}
                <div className="flex-grow" />

                <footer className="mt-16 h-24 text-center text-sm text-gray-500 main-page-padding">
                    &copy; {new Date().getFullYear()} DGLIP
                </footer>
            </body>
        </html>
    );
}
